Parameters:
  NameOfService:
    Description: "The name of the service this stake is to be used for."
    Type: String
  KeyName: 
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-1853ac65
    us-west-1:
      AMI: ami-bf5540df
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId: 
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - AMI
      Tags:
      - Key: "Name"
        Value: !Ref NameOfService
      - Key: "Region"
        Value: !Ref AWS::Region
      KeyName: !Ref KeyName
      SecurityGroups:
      - !Ref MySecurityGroup
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enahble SSH Access Via Port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
Outputs:
  ServerDns:
    Value: !GetAtt
      - EC2Instance
      - PublicDnsName